micronaut:
  application:
    name: calMixer
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /oas3/**
netty:
  default:
    allocator:
      max-order: 3
